<?php

use XcVm\Core\Auth\Authorization;

$xtreampiPageScripts = ['assets/xtreampi/bouquet-order.js'];
$xtreampiCanOrder = Authorization::check('adv', 'bouquet_order');
$xtreampiBouquets = is_array($bouquets ?? null) ? $bouquets : [];
?>
<section class="sc-bouquet-order" data-sc-bouquet-order><div class="sc-page-heading"><div><p class="sc-eyebrow">Content access</p><h1>Bouquet order</h1></div><div class="sc-page-actions"><a class="sc-button sc-button-secondary" href="bouquets"><i class="fe-chevron-left" aria-hidden="true"></i> Back to bouquets</a></div></div><form class="sc-form" action="post.php?action=bouquet_order&amp;referer=bouquets" method="post"><input type="hidden" name="bouquet_order_array" value="[]"><section class="sc-form-section"><div class="sc-section-heading"><div><h2>Connection order</h2><p class="sc-section-copy">Drag bouquets into the default order used by new lines and packages.</p></div><button class="sc-button sc-button-secondary" type="button" data-sc-bouquet-sort-name><i class="fe-list" aria-hidden="true"></i> Sort A–Z</button></div><ol class="sc-sort-list" data-sc-bouquet-order-list><?php foreach ($xtreampiBouquets as $xtreampiBouquet): ?><li draggable="true" data-bouquet-id="<?php echo (int) $xtreampiBouquet['id']; ?>"><span class="sc-sort-handle" title="Drag to reorder"><i class="fe-menu" aria-hidden="true"></i></span><div><strong><?php echo htmlspecialchars((string) $xtreampiBouquet['bouquet_name'], ENT_QUOTES, 'UTF-8'); ?></strong><small>#<?php echo (int) $xtreampiBouquet['id']; ?></small></div><span data-sc-bouquet-order-position></span></li><?php endforeach; ?></ol></section><section class="sc-form-section"><h2>Apply to existing access</h2><label class="sc-selection-card"><input type="checkbox" name="confirmReplace"><span><strong>Update all existing lines and packages</strong><small>This rewrites their bouquet order to match the new default. Leave unchecked to apply only to new lines and packages.</small></span></label></section><div class="sc-form-error" data-sc-bouquet-order-error hidden></div><div class="sc-form-actions"><?php if ($xtreampiCanOrder): ?><button class="sc-button sc-button-primary" type="submit">Save order</button><?php endif; ?><a class="sc-button sc-button-secondary" href="bouquets">Cancel</a></div></form></section>
