<?php

use XcVm\Domain\Server\ServerRepository;
use XcVm\Domain\Stream\StreamConfigRepository;

$xtreampiPageScripts = ['assets/xtreampi/stream.js', 'assets/xtreampi/movie-browser.js', 'assets/xtreampi/episode.js'];
$xtreampiEpisode = is_array($rEpisode ?? null) ? $rEpisode : [];
$xtreampiEpisodeProperties = is_array($xtreampiEpisode['properties'] ?? null) ? $xtreampiEpisode['properties'] : [];
$xtreampiEpisodeEditing = intval($xtreampiEpisode['id'] ?? 0) > 0;
$xtreampiEpisodeSource = json_decode((string) ($xtreampiEpisode['stream_source'] ?? '[]'), true);
$xtreampiEpisodeSource = is_array($xtreampiEpisodeSource) ? (string) ($xtreampiEpisodeSource[0] ?? '') : '';
$xtreampiEpisodeSubtitle = '';
$xtreampiEpisodeSubtitles = json_decode((string) ($xtreampiEpisode['movie_subtitles'] ?? ''), true);
if (!empty($xtreampiEpisodeSubtitles['location']) && !empty($xtreampiEpisodeSubtitles['files'][0])) $xtreampiEpisodeSubtitle = 's:' . $xtreampiEpisodeSubtitles['location'] . ':' . $xtreampiEpisodeSubtitles['files'][0];
$xtreampiEpisodeParents = [];
foreach ($rServerTree as $node) if (ctype_digit((string) ($node['id'] ?? ''))) $xtreampiEpisodeParents[(int) $node['id']] = (string) ($node['parent'] ?? 'offline');
$xtreampiEpisodeServers = ServerRepository::getStreamingSimple($rPermissions, 'all');
$xtreampiEpisodeValue = static fn(string $key, string $default = ''): string => htmlspecialchars((string) ($xtreampiEpisode[$key] ?? $default), ENT_QUOTES, 'UTF-8');
$xtreampiEpisodeProperty = static fn(string $key, string $default = ''): string => htmlspecialchars((string) ($xtreampiEpisodeProperties[$key] ?? $default), ENT_QUOTES, 'UTF-8');
$xtreampiEpisodeRuntime = $xtreampiEpisodeProperties['duration_secs'] ?? 0;
$xtreampiEpisodeRuntime = $xtreampiEpisodeRuntime ? (string) intdiv((int) $xtreampiEpisodeRuntime, 60) : '';
?>
<section class="sc-episode-editor" data-sc-stream-editor data-sc-movie-editor data-sc-episode-editor data-sc-series-tmdb-id="<?php echo intval($rSeriesArr['tmdb_id'] ?? 0); ?>" data-sc-series-runtime="<?php echo intval($rSeriesArr['episode_run_time'] ?? 0); ?>" data-sc-tmdb-language="<?php echo htmlspecialchars((string) ($rSeriesArr['tmdb_language'] ?? $rSettings['tmdb_language'] ?? ''), ENT_QUOTES, 'UTF-8'); ?>">
    <div class="sc-page-heading"><div><p class="sc-eyebrow">Series management</p><h1><?php echo $xtreampiEpisodeEditing ? 'Edit episode' : 'Add episode'; ?></h1></div><div class="sc-page-actions"><a class="sc-button sc-button-secondary" href="episodes?series=<?php echo intval($rSeriesArr['id']); ?>"><i class="fe-chevron-left" aria-hidden="true"></i> Back to episodes</a></div></div>
    <form class="sc-form sc-line-form" action="post.php?action=episode&amp;referer=episodes%3Fseries%3D<?php echo intval($rSeriesArr['id']); ?>" method="post">
        <?php if ($xtreampiEpisodeEditing): ?><input type="hidden" name="edit" value="<?php echo intval($xtreampiEpisode['id']); ?>"><?php endif; ?>
        <input type="hidden" name="series" value="<?php echo intval($rSeriesArr['id']); ?>"><input type="hidden" name="tmdb_id" value="<?php echo $xtreampiEpisodeProperty('tmdb_id'); ?>"><input type="hidden" name="server_tree_data" value=""><input type="hidden" name="external_push" value="{}">
        <section class="sc-form-section"><h2>Episode details</h2><div class="sc-form-grid">
            <label class="sc-form-span">Series<input type="text" value="<?php echo htmlspecialchars((string) ($rSeriesArr['title'] ?? ''), ENT_QUOTES, 'UTF-8'); ?>" readonly></label>
            <label>Season number<input id="season_num" type="number" name="season_num" min="0" required value="<?php echo $xtreampiEpisodeValue('season'); ?>"></label>
            <?php if (!empty($rSettings['tmdb_api_key']) && !empty($rSeriesArr['tmdb_id'])): ?>
                <div class="sc-tmdb-autocomplete" data-sc-episode-tmdb><label>Episode number<span class="sc-tmdb-input-wrap"><input id="episode" type="number" name="episode" min="0" required value="<?php echo $xtreampiEpisodeValue('episode'); ?>"><button class="sc-tmdb-result-count" type="button" data-sc-episode-tmdb-toggle hidden><span data-sc-episode-tmdb-count></span><i class="fe-chevron-down" aria-hidden="true"></i></button></span></label><div class="sc-tmdb-results" data-sc-episode-tmdb-results hidden></div></div>
            <?php else: ?>
                <label>Episode number<input id="episode" type="number" name="episode" min="0" required value="<?php echo $xtreampiEpisodeValue('episode'); ?>"></label>
            <?php endif; ?>
            <label class="sc-form-span">Episode name<input id="stream_display_name" type="text" name="stream_display_name" required value="<?php echo $xtreampiEpisodeValue('stream_display_name'); ?>"></label>
            <label class="sc-form-span">Episode path or URL<span class="sc-input-action"><input id="stream_source" type="text" name="stream_source" required value="<?php echo htmlspecialchars($xtreampiEpisodeSource, ENT_QUOTES, 'UTF-8'); ?>" placeholder="https://example.com/episode.mkv or s:server_id:/path/episode.mkv"><button class="sc-button sc-button-secondary" type="button" data-sc-file-browser-open data-sc-file-target="stream_source" data-sc-file-filter="video"><i class="fe-folder" aria-hidden="true"></i> Browse</button></span></label>
            <label class="sc-form-span">Notes<textarea name="notes" rows="3"><?php echo $xtreampiEpisodeValue('notes'); ?></textarea></label>
        </div></section>
        <section class="sc-form-section"><h2>Metadata</h2>
            <div class="sc-form-grid"><label>Still image URL<input id="movie_image" type="url" name="movie_image" value="<?php echo $xtreampiEpisodeProperty('movie_image'); ?>"></label><label>Release date<input id="release_date" type="text" name="release_date" value="<?php echo $xtreampiEpisodeProperty('release_date'); ?>"></label><label class="sc-form-span">Plot<textarea id="plot" name="plot" rows="5"><?php echo $xtreampiEpisodeProperty('plot'); ?></textarea></label><label>Runtime (minutes)<input id="episode_run_time" type="number" name="episode_run_time" min="0" value="<?php echo htmlspecialchars($xtreampiEpisodeRuntime, ENT_QUOTES, 'UTF-8'); ?>"></label><label>Rating<input id="rating" type="number" name="rating" min="0" max="10" step="0.1" value="<?php echo $xtreampiEpisodeProperty('rating'); ?>"></label></div>
        </section>
        <section class="sc-form-section"><h2>Processing</h2><div class="sc-form-grid"><label>Transcode profile<select id="transcode_profile_id" name="transcode_profile_id"><option value="0">Disabled</option><?php foreach (StreamConfigRepository::getTranscodeProfiles() as $profile): ?><option value="<?php echo intval($profile['profile_id']); ?>"<?php echo intval($xtreampiEpisode['transcode_profile_id'] ?? 0) === intval($profile['profile_id']) ? ' selected' : ''; ?>><?php echo htmlspecialchars((string) $profile['profile_name'], ENT_QUOTES, 'UTF-8'); ?></option><?php endforeach; ?></select></label><label>Target container<select id="target_container" name="target_container"><?php foreach (['mp4','mkv','avi','mpg','flv','3gp','m4v','wmv','mov','ts'] as $container): ?><option value="<?php echo $container; ?>"<?php echo ($xtreampiEpisode['target_container'] ?? 'mp4') === $container ? ' selected' : ''; ?>><?php echo $container; ?></option><?php endforeach; ?></select></label><label class="sc-form-span">Subtitle location<span class="sc-input-action"><input id="movie_subtitles" type="text" name="movie_subtitles" value="<?php echo htmlspecialchars($xtreampiEpisodeSubtitle, ENT_QUOTES, 'UTF-8'); ?>" placeholder="s:server_id:subtitle.srt"><button class="sc-button sc-button-secondary" type="button" data-sc-file-browser-open data-sc-file-target="movie_subtitles" data-sc-file-filter="subs"><i class="fe-folder" aria-hidden="true"></i> Browse</button></span></label></div><div class="sc-package-options sc-line-switches"><?php foreach ([['direct_source','Direct source'],['direct_proxy','Direct stream'],['read_native','Native frames'],['movie_symlink','Create symlink'],['remove_subtitles','Remove existing subtitles']] as [$key,$label]): ?><label class="sc-selection-card"><input id="<?php echo $key; ?>" type="checkbox" name="<?php echo $key; ?>"<?php echo !empty($xtreampiEpisode[$key]) ? ' checked' : ''; ?>><span><strong><?php echo $label; ?></strong></span></label><?php endforeach; ?></div></section>
        <section class="sc-form-section"><h2>Server placement</h2><p class="sc-section-copy">Select the server that processes this episode, then optionally use it as the upstream source for other servers.</p><div class="sc-server-placement"><?php foreach ($xtreampiEpisodeServers as $server): $id = intval($server['id']); $parent = $xtreampiEpisodeParents[$id] ?? 'offline'; ?><div class="sc-server-placement-row" data-server-id="<?php echo $id; ?>"><strong><?php echo htmlspecialchars((string) $server['server_name'], ENT_QUOTES, 'UTF-8'); ?></strong><label>Upstream<select data-server-parent><option value="offline"<?php echo $parent === 'offline' ? ' selected' : ''; ?>>Disabled</option><option value="source"<?php echo $parent === 'source' ? ' selected' : ''; ?>>Process source</option><?php foreach ($xtreampiEpisodeServers as $upstream): if ((int) $upstream['id'] === $id) continue; ?><option value="<?php echo intval($upstream['id']); ?>"<?php echo (string) $parent === (string) intval($upstream['id']) ? ' selected' : ''; ?>><?php echo htmlspecialchars((string) $upstream['server_name'], ENT_QUOTES, 'UTF-8'); ?></option><?php endforeach; ?></select></label></div><?php endforeach; ?></div><label class="sc-selection-card" style="margin-top: 16px;"><input type="checkbox" name="restart_on_edit"><span><strong><?php echo $xtreampiEpisodeEditing ? 'Reprocess after saving' : 'Process episode now'; ?></strong><small>Queue this episode on the assigned servers.</small></span></label></section>
        <div class="sc-form-error" data-stream-error role="alert" hidden></div><div class="sc-form-actions"><button class="sc-button sc-button-primary" type="submit"><?php echo $xtreampiEpisodeEditing ? 'Save episode' : 'Add episode'; ?></button><a class="sc-button sc-button-secondary" href="episodes?series=<?php echo intval($rSeriesArr['id']); ?>">Cancel</a></div>
    </form>
</section>
<dialog class="sc-playlist-dialog sc-file-browser-dialog" data-sc-file-browser-dialog><div class="sc-dialog-heading"><div><p class="sc-eyebrow">Server files</p><h2 data-sc-file-browser-title>Browse episode files</h2></div><button class="sc-dialog-close" type="button" data-sc-file-browser-close aria-label="Close"><i class="fe-x" aria-hidden="true"></i></button></div><div class="sc-dialog-body"><div class="sc-form-grid"><label>Server<select data-sc-file-browser-server><?php foreach ($xtreampiEpisodeServers as $server): ?><option value="<?php echo intval($server['id']); ?>"><?php echo htmlspecialchars((string) $server['server_name'], ENT_QUOTES, 'UTF-8'); ?></option><?php endforeach; ?></select></label><label>Directory<span class="sc-input-action"><input type="text" value="/" data-sc-file-browser-path><button class="sc-button sc-button-secondary" type="button" data-sc-file-browser-load>Open</button></span></label></div><div class="sc-file-browser-columns"><section><h3>Folders</h3><div data-sc-file-browser-dirs class="sc-file-browser-list"></div></section><section><h3 data-sc-file-browser-files-heading>Compatible files</h3><div data-sc-file-browser-files class="sc-file-browser-list"></div></section></div></div></dialog>
