<?php

use XcVm\Domain\Bouquet\BouquetService;
use XcVm\Domain\Server\ServerRepository;

$xtreampiPageScripts = ['assets/xtreampi/movie-mass.js'];
$xtreampiMassCategories = array_map(static fn(array $item): array => ['id' => (int) $item['id'], 'text' => (string) $item['category_name']], $rCategories);
$xtreampiMassBouquets = array_map(static fn(array $item): array => ['id' => (int) $item['id'], 'text' => (string) $item['bouquet_name']], BouquetService::getAllSimple());
$xtreampiMassServers = ServerRepository::getStreamingSimple($rPermissions, 'all');
?>
<section class="sc-movie-mass" data-sc-movie-mass data-endpoint="table">
    <div class="sc-page-heading"><div><p class="sc-eyebrow">Content management</p><h1>Mass edit movies <span data-sc-mass-count></span></h1></div><div class="sc-page-actions"><a class="sc-button sc-button-secondary" href="movies"><i class="fe-chevron-left" aria-hidden="true"></i> Back to movies</a></div></div>
    <form class="sc-form sc-line-form" action="post.php?action=movie_mass" method="post">
        <input type="hidden" name="streams" data-sc-mass-streams>
        <input type="hidden" name="server_tree_data" data-sc-mass-servers>
        <section class="sc-form-section"><h2>Select movies</h2><div class="sc-toolbar">
            <label class="sc-search-field"><i class="fe-search" aria-hidden="true"></i><span class="sc-visually-hidden">Search movies</span><input type="search" placeholder="Search movies" data-sc-mass-search></label>
            <label class="sc-filter-field"><span>Server</span><select data-sc-mass-server><option value="">All servers</option><option value="-1">No server</option><?php foreach ($xtreampiMassServers as $server): ?><option value="<?php echo (int) $server['id']; ?>"><?php echo htmlspecialchars((string) $server['server_name'], ENT_QUOTES, 'UTF-8'); ?></option><?php endforeach; ?></select></label>
            <label class="sc-filter-field"><span>Category</span><select data-sc-mass-category><option value="">All categories</option><?php foreach ($xtreampiMassCategories as $category): ?><option value="<?php echo $category['id']; ?>"><?php echo htmlspecialchars($category['text'], ENT_QUOTES, 'UTF-8'); ?></option><?php endforeach; ?></select></label>
            <label class="sc-filter-field"><span>Status</span><select data-sc-mass-status><option value="">All statuses</option><option value="1">Encoded</option><option value="2">Encoding</option><option value="3">Down</option><option value="4">Ready</option><option value="5">Direct</option></select></label>
        </div><div class="sc-data-panel"><div class="sc-table-scroll"><table class="sc-data-table sc-mass-table"><thead><tr><th class="sc-mass-select"><input type="checkbox" aria-label="Select visible movies" data-sc-mass-select-page></th><th>Movie</th><th>Server</th><th>Status</th></tr></thead><tbody data-sc-mass-rows><tr><td class="sc-table-state" colspan="4">Loading movies…</td></tr></tbody></table></div><footer class="sc-table-footer"><span data-sc-mass-range>Loading…</span><div class="sc-pagination"><button type="button" data-sc-mass-prev>Previous</button><span data-sc-mass-page>Page 1</span><button type="button" data-sc-mass-next>Next</button></div></footer></div></section>

        <section class="sc-form-section"><h2>Changes to apply</h2><p class="sc-section-copy">Only enabled changes are applied to the selected movies.</p><div class="sc-mass-change-grid">
            <div class="sc-mass-change" data-sc-mass-change><label class="sc-change-toggle"><input type="checkbox" name="c_category_id" data-sc-mass-enable> Replace categories</label><div data-sc-mass-controls hidden><div class="sc-static-picker" data-static-picker data-name="category_id[]" data-create-field="" data-allow-create="0"><script type="application/json" data-static-items><?php echo json_encode($xtreampiMassCategories, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT); ?></script><label>Categories<input type="search" placeholder="Search categories" autocomplete="off" data-static-search></label><div class="sc-owner-options" data-static-options hidden></div><div class="sc-token-list" data-static-values></div><p data-static-empty>Nothing selected.</p></div><label>Mode<select name="category_id_type"><option value="SET">Replace</option><option value="ADD">Add</option><option value="DEL">Remove</option></select></label></div></div>
            <div class="sc-mass-change" data-sc-mass-change><label class="sc-change-toggle"><input type="checkbox" name="c_bouquets" data-sc-mass-enable> Change bouquets</label><div data-sc-mass-controls hidden><div class="sc-static-picker" data-static-picker data-name="bouquets[]" data-create-field="" data-allow-create="0"><script type="application/json" data-static-items><?php echo json_encode($xtreampiMassBouquets, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT); ?></script><label>Bouquets<input type="search" placeholder="Search bouquets" autocomplete="off" data-static-search></label><div class="sc-owner-options" data-static-options hidden></div><div class="sc-token-list" data-static-values></div><p data-static-empty>Nothing selected.</p></div><label>Mode<select name="bouquets_type"><option value="SET">Replace</option><option value="ADD">Add</option><option value="DEL">Remove</option></select></label></div></div>
            <?php foreach ([['direct_source', 'Direct source'], ['direct_proxy', 'Direct stream'], ['movie_symlink', 'Create symlink'], ['read_native', 'Native frames'], ['remove_subtitles', 'Remove existing subtitles']] as [$key, $label]): ?><div class="sc-mass-change" data-sc-mass-change><label class="sc-change-toggle"><input type="checkbox" name="c_<?php echo $key; ?>" data-sc-mass-enable> Change <?php echo $label; ?></label><div data-sc-mass-controls hidden><label class="sc-selection-card"><input type="checkbox" name="<?php echo $key; ?>"><span><strong><?php echo $label; ?></strong><small>Enabled for every selected movie.</small></span></label></div></div><?php endforeach; ?>
            <div class="sc-mass-change" data-sc-mass-change><label class="sc-change-toggle"><input type="checkbox" name="c_target_container" data-sc-mass-enable> Change target container</label><div data-sc-mass-controls hidden><label>Target container<select name="target_container"><?php foreach (['mp4', 'mkv', 'avi', 'mpg', 'flv', '3gp', 'm4v', 'wmv', 'mov', 'ts'] as $container): ?><option value="<?php echo $container; ?>"><?php echo $container; ?></option><?php endforeach; ?></select></label></div></div>
            <div class="sc-mass-change" data-sc-mass-change><label class="sc-change-toggle"><input type="checkbox" name="c_transcode_profile_id" data-sc-mass-enable> Change transcode profile</label><div data-sc-mass-controls hidden><label>Transcode profile<select name="transcode_profile_id"><option value="0">Disabled</option><?php foreach ($rTranscodeProfiles as $profile): ?><option value="<?php echo (int) $profile['profile_id']; ?>"><?php echo htmlspecialchars((string) $profile['profile_name'], ENT_QUOTES, 'UTF-8'); ?></option><?php endforeach; ?></select></label></div></div>
        </div></section>
        <section class="sc-form-section"><h2>Server placement</h2><div class="sc-mass-change" data-sc-mass-change><label class="sc-change-toggle"><input type="checkbox" name="c_server_tree" data-sc-mass-enable> Change assigned servers</label><div data-sc-mass-controls hidden><label>Mode<select name="server_type"><option value="SET">Replace</option><option value="ADD">Add</option><option value="DEL">Remove</option></select></label><div class="sc-server-checklist"><?php foreach ($xtreampiMassServers as $server): ?><label><input type="checkbox" value="<?php echo (int) $server['id']; ?>" data-sc-mass-server-choice> <?php echo htmlspecialchars((string) $server['server_name'], ENT_QUOTES, 'UTF-8'); ?></label><?php endforeach; ?></div></div></div><div class="sc-package-options sc-line-switches"><label class="sc-selection-card"><input type="checkbox" name="reencode_on_edit"><span><strong>Re-encode after editing</strong></span></label><label class="sc-selection-card"><input type="checkbox" name="reprocess_tmdb"><span><strong>Refresh TMDB metadata</strong></span></label></div></section>
        <div class="sc-form-error" data-sc-mass-error role="alert" hidden></div><div class="sc-form-actions"><button class="sc-button sc-button-primary" type="submit">Apply changes</button><button class="sc-button sc-button-secondary" type="button" data-sc-mass-clear>Clear selection</button></div>
    </form>
</section>
