<?php
$xtreampiPageScripts = ['assets/xtreampi/process_monitor.js'];
$xtreampiServerId = intval($_GET['server'] ?? (defined('SERVER_ID') ? SERVER_ID : 1));
$xtreampiServers = is_array($rServers ?? null) ? $rServers : [];
$xtreampiFilesystem = is_array($rFS ?? null) ? $rFS : [];
$xtreampiProcesses = is_array($rProcesses ?? null) ? $rProcesses : [];
$xtreampiDuration = static function ($seconds): string { $seconds = max(0, intval($seconds)); $days = intdiv($seconds, 86400); $hours = intdiv($seconds, 3600) % 24; $minutes = intdiv($seconds, 60) % 60; $seconds %= 60; return $days > 0 ? sprintf('%02dd %02dh %02dm', $days, $hours, $minutes) : sprintf('%02dh %02dm %02ds', $hours, $minutes, $seconds); };
?>
<section class="sc-process-monitor" data-sc-process-monitor>
<div class="sc-page-heading"><div><p class="sc-eyebrow">System</p><h1>Process Monitor</h1></div><div class="sc-page-actions"><a class="sc-button sc-button-secondary" href="process_monitor?server=<?php echo $xtreampiServerId; ?>"><i class="fe-refresh-cw" aria-hidden="true"></i> Refresh</a></div></div>
<?php if ($xtreampiFilesystem): ?><div class="sc-data-panel sc-process-filesystem"><div class="sc-table-scroll"><table class="sc-data-table"><thead><tr><th>Mount point</th><th>Size</th><th>Used</th><th>Available</th><th>Used %</th><th>Actions</th></tr></thead><tbody><?php foreach ($xtreampiFilesystem as $xtreampiFs): ?><tr><td><?php echo htmlspecialchars((string) ($xtreampiFs['mount'] ?? '—'), ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo htmlspecialchars((string) ($xtreampiFs['size'] ?? '—'), ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo htmlspecialchars((string) ($xtreampiFs['used'] ?? '—'), ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo htmlspecialchars((string) ($xtreampiFs['avail'] ?? '—'), ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo htmlspecialchars((string) ($xtreampiFs['percentage'] ?? '0%'), ENT_QUOTES, 'UTF-8'); ?></td><td class="sc-table-actions">—</td></tr><?php endforeach; ?></tbody></table></div></div><?php endif; ?>
<div class="sc-data-panel"><div class="sc-process-toolbar"><label class="sc-search-field"><i class="fe-search" aria-hidden="true"></i><span class="sc-visually-hidden">Search processes</span><input type="search" placeholder="Search processes…" data-sc-process-search></label><label class="sc-filter-field"><span>Server</span><select onchange="location.href='process_monitor?server='+encodeURIComponent(this.value)"><?php foreach ($xtreampiServers as $xtreampiServer): ?><option value="<?php echo intval($xtreampiServer['id']); ?>"<?php echo intval($xtreampiServer['id']) === $xtreampiServerId ? ' selected' : ''; ?>><?php echo htmlspecialchars((string) ($xtreampiServer['server_name'] ?? 'Server'), ENT_QUOTES, 'UTF-8'); ?></option><?php endforeach; ?></select></label></div><div class="sc-table-scroll"><table class="sc-data-table"><thead><tr><th>PID</th><th>Type</th><th>Process</th><th>CPU (%)</th><th>MEM (MB)</th><th>Runtime</th><th>CPU time</th><th>Actions</th></tr></thead><tbody data-sc-process-rows><?php foreach ($xtreampiProcesses as $xtreampiProcess): ?><tr data-sc-process-row data-search="<?php echo htmlspecialchars(strtolower((string) ($xtreampiProcess['pid'] ?? '') . ' ' . (string) ($xtreampiProcess['command'] ?? '')), ENT_QUOTES, 'UTF-8'); ?>"><td><?php echo intval($xtreampiProcess['pid'] ?? 0); ?></td><td>System</td><td><?php echo htmlspecialchars((string) ($xtreampiProcess['command'] ?? '—'), ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo number_format((float) ($xtreampiProcess['cpu'] ?? 0), 2); ?>%<small class="sc-table-muted"><br>avg: <?php echo number_format((float) ($xtreampiProcess['load_average'] ?? 0), 2); ?>%</small></td><td><?php echo number_format((float) ($xtreampiProcess['rss'] ?? 0) / 1024, 0); ?></td><td><?php echo $xtreampiDuration($xtreampiProcess['etime'] ?? 0); ?></td><td><?php echo $xtreampiDuration($xtreampiProcess['time'] ?? 0); ?></td><td class="sc-table-actions">—</td></tr><?php endforeach; ?><?php if (!$xtreampiProcesses): ?><tr><td class="sc-table-state" colspan="8">Unable to retrieve process list. Try refreshing the monitor.</td></tr><?php endif; ?></tbody></table></div></div>
</section>
