<?php

use XcVm\Domain\Bouquet\BouquetService;
use XcVm\Domain\Stream\CategoryService;

$xtreampiPageScripts = ['assets/xtreampi/stream.js', 'assets/xtreampi/radio.js'];
$xtreampiRadio = is_array($rStation ?? null) ? $rStation : [];
$xtreampiRadioEditing = (int) ($xtreampiRadio['id'] ?? 0) > 0;
$xtreampiRadioOptions = is_array($rStationOptions ?? null) ? $rStationOptions : [];
$xtreampiRadioCategories = CategoryService::getAllByType('radio');
$xtreampiRadioBouquets = BouquetService::getAllSimple();
$xtreampiRadioCategoryIDs = array_map('intval', json_decode((string) ($xtreampiRadio['category_id'] ?? '[]'), true) ?: []);
$xtreampiRadioBouquetIDs = [];
foreach ($xtreampiRadioBouquets as $xtreampiRadioBouquet) if (in_array((int) ($xtreampiRadio['id'] ?? 0), array_map('intval', json_decode((string) ($xtreampiRadioBouquet['bouquet_radios'] ?? '[]'), true) ?: []), true)) $xtreampiRadioBouquetIDs[] = (int) $xtreampiRadioBouquet['id'];
$xtreampiRadioSource = json_decode((string) ($xtreampiRadio['stream_source'] ?? '[]'), true);
$xtreampiRadioSource = is_array($xtreampiRadioSource) ? (string) ($xtreampiRadioSource[0] ?? '') : '';
$xtreampiRadioAuto = json_decode((string) ($xtreampiRadio['auto_restart'] ?? '[]'), true) ?: [];
$xtreampiRadioParents = [];
foreach (($rServerTree ?? []) as $xtreampiRadioNode) if (ctype_digit((string) ($xtreampiRadioNode['id'] ?? ''))) $xtreampiRadioParents[(int) $xtreampiRadioNode['id']] = (string) ($xtreampiRadioNode['parent'] ?? 'offline');
$xtreampiRadioOnDemand = array_map('intval', $rOnDemand ?? []);
$xtreampiRadioValue = static fn(string $key, string $default = ''): string => htmlspecialchars((string) ($xtreampiRadio[$key] ?? $default), ENT_QUOTES, 'UTF-8');
$xtreampiRadioPicker = static function (string $label, string $name, string $createField, array $items, array $selected): void { $map=[]; foreach ($items as $item) $map[(int) $item['id']] = (string) $item['text']; ?>
    <div class="sc-static-picker" data-static-picker data-name="<?php echo htmlspecialchars($name, ENT_QUOTES, 'UTF-8'); ?>" data-create-field="<?php echo htmlspecialchars($createField, ENT_QUOTES, 'UTF-8'); ?>" data-create-label="<?php echo htmlspecialchars(rtrim($label, 's'), ENT_QUOTES, 'UTF-8'); ?>"><script type="application/json" data-static-items><?php echo json_encode($items, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT); ?></script><label><?php echo htmlspecialchars($label, ENT_QUOTES, 'UTF-8'); ?><input type="search" placeholder="Search or create <?php echo strtolower(htmlspecialchars(rtrim($label, 's'), ENT_QUOTES, 'UTF-8')); ?>" autocomplete="off" data-static-search></label><div class="sc-owner-options" data-static-options hidden></div><div class="sc-token-list" data-static-values><?php foreach ($selected as $id): if (!isset($map[(int) $id])) continue; ?><span><?php echo htmlspecialchars($map[(int) $id], ENT_QUOTES, 'UTF-8'); ?><input type="hidden" name="<?php echo htmlspecialchars($name, ENT_QUOTES, 'UTF-8'); ?>" value="<?php echo (int) $id; ?>"><button type="button" aria-label="Remove">×</button></span><?php endforeach; ?></div><p data-static-empty<?php echo $selected ? ' hidden' : ''; ?>>Nothing selected.</p></div>
<?php };
$xtreampiRadioCategoryOptions = array_map(static fn(array $item): array => ['id'=>(int)$item['id'], 'text'=>(string)$item['category_name']], $xtreampiRadioCategories);
$xtreampiRadioBouquetOptions = array_map(static fn(array $item): array => ['id'=>(int)$item['id'], 'text'=>(string)$item['bouquet_name']], $xtreampiRadioBouquets);
?>
<section class="sc-radio-editor" data-sc-stream-editor data-sc-radio-editor>
    <div class="sc-page-heading"><div><p class="sc-eyebrow">Content management</p><h1><?php echo $xtreampiRadioEditing ? 'Edit radio station' : 'Add radio station'; ?></h1></div><div class="sc-page-actions"><a class="sc-button sc-button-secondary" href="radios"><i class="fe-chevron-left" aria-hidden="true"></i> Back to radio</a></div></div>
    <form class="sc-form sc-line-form" action="post.php?action=radio&amp;referer=radios" method="post">
        <?php if ($xtreampiRadioEditing): ?><input type="hidden" name="edit" value="<?php echo (int) $xtreampiRadio['id']; ?>"><?php endif; ?>
        <input type="hidden" name="server_tree_data" value=""><input type="hidden" name="external_push" value="{}"><input type="hidden" name="category_create_list" value="[]"><input type="hidden" name="bouquet_create_list" value="[]"><input type="hidden" name="bouquets[]" value="">
        <section class="sc-form-section"><h2>Station details</h2><div class="sc-form-grid"><label>Station name<input id="stream_display_name" name="stream_display_name" required value="<?php echo $xtreampiRadioValue('stream_display_name'); ?>"></label><label>Station logo URL<input name="stream_icon" type="url" value="<?php echo $xtreampiRadioValue('stream_icon'); ?>"></label><label class="sc-form-span">Station URL<input name="stream_source[]" required value="<?php echo htmlspecialchars($xtreampiRadioSource, ENT_QUOTES, 'UTF-8'); ?>" placeholder="https://example.com/radio.mp3"></label><?php $xtreampiRadioPicker('Categories', 'category_id[]', 'category_create_list', $xtreampiRadioCategoryOptions, $xtreampiRadioCategoryIDs); ?><?php $xtreampiRadioPicker('Bouquets', 'bouquets[]', 'bouquet_create_list', $xtreampiRadioBouquetOptions, $xtreampiRadioBouquetIDs); ?><label class="sc-form-span">Notes<textarea name="notes" rows="3"><?php echo $xtreampiRadioValue('notes'); ?></textarea></label></div></section>
        <section class="sc-form-section"><h2>Processing</h2><div class="sc-form-grid"><label>Custom channel SID<input name="custom_sid" value="<?php echo $xtreampiRadioValue('custom_sid'); ?>"></label><label>On-demand probe size<input name="probesize_ondemand" type="number" min="0" value="<?php echo $xtreampiRadioValue('probesize_ondemand', '128000'); ?>"></label><label class="sc-form-span">Custom FFmpeg command<input name="custom_ffmpeg" value="<?php echo $xtreampiRadioValue('custom_ffmpeg'); ?>"></label><label>User agent<input name="user_agent" value="<?php echo htmlspecialchars((string) ($xtreampiRadioOptions[1]['value'] ?? ''), ENT_QUOTES, 'UTF-8'); ?>"></label><label>HTTP proxy<input name="http_proxy" value="<?php echo htmlspecialchars((string) ($xtreampiRadioOptions[2]['value'] ?? ''), ENT_QUOTES, 'UTF-8'); ?>"></label><label>Cookies<input name="cookie" value="<?php echo htmlspecialchars((string) ($xtreampiRadioOptions[17]['value'] ?? ''), ENT_QUOTES, 'UTF-8'); ?>"></label><label>HTTP headers<input name="headers" value="<?php echo htmlspecialchars((string) ($xtreampiRadioOptions[19]['value'] ?? ''), ENT_QUOTES, 'UTF-8'); ?>"></label><label>Force audio codec<input name="force_input_acodec" value="<?php echo htmlspecialchars((string) ($xtreampiRadioOptions[20]['value'] ?? ''), ENT_QUOTES, 'UTF-8'); ?>"></label></div><div class="sc-package-options sc-line-switches"><label class="sc-selection-card"><input type="checkbox" name="direct_source" data-sc-radio-direct<?php echo !empty($xtreampiRadio['direct_source']) ? ' checked' : ''; ?>><span><strong>Direct source</strong><small>Redirect clients to the source without processing it.</small></span></label><label class="sc-selection-card"><input type="checkbox" name="skip_ffprobe"<?php echo !empty($xtreampiRadioOptions[21]) ? ' checked' : ''; ?>><span><strong>Skip media probe</strong></span></label></div></section>
        <section class="sc-form-section"><h2>Automatic restart</h2><div class="sc-form-grid"><label>Restart time<input name="time_to_restart" type="time" value="<?php echo htmlspecialchars((string) ($xtreampiRadioAuto['at'] ?? '06:00'), ENT_QUOTES, 'UTF-8'); ?>"></label><div class="sc-selection-grid sc-form-span"><?php foreach (['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'] as $day): ?><label class="sc-check"><input type="checkbox" name="days_to_restart[]" value="<?php echo $day; ?>"<?php echo in_array($day, $xtreampiRadioAuto['days'] ?? [], true) ? ' checked' : ''; ?>><span><?php echo $day; ?></span></label><?php endforeach; ?></div></div></section>
        <section class="sc-form-section"><h2>Server placement</h2><div class="sc-server-placement"><?php foreach (($rServers ?? []) as $server): $id=(int)$server['id']; ?><div class="sc-server-placement-row" data-server-id="<?php echo $id; ?>"><strong><?php echo htmlspecialchars((string)$server['server_name'], ENT_QUOTES, 'UTF-8'); ?></strong><label>Upstream<select data-server-parent><option value="offline"<?php echo ($xtreampiRadioParents[$id] ?? 'offline') === 'offline' ? ' selected' : ''; ?>>Disabled</option><option value="source"<?php echo ($xtreampiRadioParents[$id] ?? '') === 'source' ? ' selected' : ''; ?>>Process source</option><?php foreach (($rServers ?? []) as $upstream): if ((int)$upstream['id'] === $id) continue; ?><option value="<?php echo (int)$upstream['id']; ?>"<?php echo (string)($xtreampiRadioParents[$id] ?? '') === (string)(int)$upstream['id'] ? ' selected' : ''; ?>><?php echo htmlspecialchars((string)$upstream['server_name'], ENT_QUOTES, 'UTF-8'); ?></option><?php endforeach; ?></select></label><label class="sc-check"><input type="checkbox" name="on_demand[]" value="<?php echo $id; ?>"<?php echo in_array($id, $xtreampiRadioOnDemand, true) ? ' checked' : ''; ?>><span>On demand</span></label></div><?php endforeach; ?></div><label class="sc-selection-card" style="margin-top:16px"><input type="checkbox" name="restart_on_edit"><span><strong><?php echo $xtreampiRadioEditing ? 'Restart after saving' : 'Start station now'; ?></strong></span></label></section>
        <div class="sc-form-error" data-stream-error role="alert" hidden></div><div class="sc-form-actions"><button class="sc-button sc-button-primary" type="submit"><?php echo $xtreampiRadioEditing ? 'Save station' : 'Add station'; ?></button><a class="sc-button sc-button-secondary" href="radios">Cancel</a></div>
    </form>
</section>
