<?php

use XcVm\Domain\Bouquet\BouquetService;
use XcVm\Domain\Stream\CategoryService;

$xtreampiPageScripts = ['assets/xtreampi/serie.js'];
$xtreampiSeries = is_array($rSeriesArr ?? null) ? $rSeriesArr : [];
$xtreampiSeriesEditing = intval($xtreampiSeries['id'] ?? 0) > 0;
$xtreampiSeriesCategories = array_map('intval', json_decode((string) ($xtreampiSeries['category_id'] ?? '[]'), true) ?: []);
$xtreampiSeriesBouquets = BouquetService::getAllSimple();
$xtreampiSeriesSelectedBouquets = [];
foreach ($xtreampiSeriesBouquets as $bouquet) if ($xtreampiSeriesEditing && in_array((int) $xtreampiSeries['id'], array_map('intval', json_decode((string) ($bouquet['bouquet_series'] ?? '[]'), true) ?: []), true)) $xtreampiSeriesSelectedBouquets[] = (int) $bouquet['id'];
$xtreampiSeriesCategoryOptions = array_map(static fn(array $item): array => ['id' => (int) $item['id'], 'text' => (string) $item['category_name']], CategoryService::getAllByType('series'));
$xtreampiSeriesBouquetOptions = array_map(static fn(array $item): array => ['id' => (int) $item['id'], 'text' => (string) $item['bouquet_name']], $xtreampiSeriesBouquets);
$xtreampiSeriesValue = static fn(string $key, string $default = ''): string => htmlspecialchars((string) ($xtreampiSeries[$key] ?? $default), ENT_QUOTES, 'UTF-8');
$xtreampiSeriesBackdrop = json_decode((string) ($xtreampiSeries['backdrop_path'] ?? '[]'), true);
if (!is_array($xtreampiSeriesBackdrop)) $xtreampiSeriesBackdrop = [];
$xtreampiRenderPicker = static function (string $label, string $name, string $createField, array $items, array $selected): void { $map = []; foreach ($items as $item) $map[(int) $item['id']] = (string) $item['text']; ?>
    <div class="sc-static-picker" data-sc-serie-picker data-name="<?php echo htmlspecialchars($name, ENT_QUOTES, 'UTF-8'); ?>" data-create-field="<?php echo htmlspecialchars($createField, ENT_QUOTES, 'UTF-8'); ?>" data-create-label="<?php echo htmlspecialchars(rtrim($label, 's'), ENT_QUOTES, 'UTF-8'); ?>"><script type="application/json" data-serie-items><?php echo json_encode($items, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT); ?></script><label><?php echo htmlspecialchars($label, ENT_QUOTES, 'UTF-8'); ?><input type="search" placeholder="Search or create <?php echo strtolower(htmlspecialchars(rtrim($label, 's'), ENT_QUOTES, 'UTF-8')); ?>" autocomplete="off" data-serie-search></label><div class="sc-owner-options" data-serie-options hidden></div><div class="sc-token-list" data-serie-values><?php foreach ($selected as $id): if (!isset($map[(int) $id])) continue; ?><span><?php echo htmlspecialchars($map[(int) $id], ENT_QUOTES, 'UTF-8'); ?><input type="hidden" name="<?php echo htmlspecialchars($name, ENT_QUOTES, 'UTF-8'); ?>" value="<?php echo (int) $id; ?>"><button type="button" aria-label="Remove">×</button></span><?php endforeach; ?></div><p data-serie-empty<?php echo $selected ? ' hidden' : ''; ?>>Nothing selected.</p></div>
<?php }; ?>
<section class="sc-serie-editor" data-sc-serie-editor>
    <div class="sc-page-heading"><div><p class="sc-eyebrow">Content management</p><h1><?php echo $xtreampiSeriesEditing ? 'Edit series' : 'Add series'; ?></h1></div><div class="sc-page-actions"><a class="sc-button sc-button-secondary" href="series"><i class="fe-chevron-left" aria-hidden="true"></i> Back to series</a></div></div>
    <form class="sc-form sc-line-form" action="post.php?action=serie&amp;referer=series" method="post">
        <?php if ($xtreampiSeriesEditing): ?><input type="hidden" name="edit" value="<?php echo (int) $xtreampiSeries['id']; ?>"><?php endif; ?><input type="hidden" name="tmdb_id" value="<?php echo $xtreampiSeriesValue('tmdb_id'); ?>"><input type="hidden" name="tmdb_language" value="<?php echo htmlspecialchars((string) ($xtreampiSeries['tmdb_language'] ?? $rSettings['tmdb_language'] ?? ''), ENT_QUOTES, 'UTF-8'); ?>"><input type="hidden" name="category_create_list" value="[]"><input type="hidden" name="bouquet_create_list" value="[]">
        <section class="sc-form-section"><h2>Series details</h2><div class="sc-form-grid"><label>Series name<input id="title" type="text" name="title" required value="<?php echo $xtreampiSeriesValue('title'); ?>"></label><label>Year<input id="year" type="text" name="year" inputmode="numeric" value="<?php echo $xtreampiSeriesValue('year'); ?>"></label><?php $xtreampiRenderPicker('Categories', 'category_id[]', 'category_create_list', $xtreampiSeriesCategoryOptions, $xtreampiSeriesCategories); ?><?php $xtreampiRenderPicker('Bouquets', 'bouquets[]', 'bouquet_create_list', $xtreampiSeriesBouquetOptions, $xtreampiSeriesSelectedBouquets); ?></div></section>
        <section class="sc-form-section"><h2>Metadata</h2><?php if (!empty($rSettings['tmdb_api_key'])): ?><div class="sc-tmdb-lookup" data-sc-serie-tmdb data-sc-tmdb-language="<?php echo htmlspecialchars((string) ($rSettings['tmdb_language'] ?? ''), ENT_QUOTES, 'UTF-8'); ?>"><div class="sc-section-heading"><div><h2>Search TMDB</h2><p class="sc-section-copy">Uses the default TMDB language configured in Settings.</p></div></div><label>Series title<input type="search" data-sc-serie-query placeholder="Search by series title" autocomplete="off"></label><div class="sc-tmdb-results" data-sc-serie-results hidden></div></div><?php endif; ?><div class="sc-form-grid" style="margin-top: 24px;"><label>Poster URL<input id="cover" type="url" name="cover" value="<?php echo $xtreampiSeriesValue('cover'); ?>"></label><label>Backdrop URL<input id="backdrop_path" type="url" name="backdrop_path" value="<?php echo htmlspecialchars((string) ($xtreampiSeriesBackdrop[0] ?? ''), ENT_QUOTES, 'UTF-8'); ?>"></label><label class="sc-form-span">Plot<textarea id="plot" name="plot" rows="5"><?php echo $xtreampiSeriesValue('plot'); ?></textarea></label><label>Cast<input id="cast" type="text" name="cast" value="<?php echo $xtreampiSeriesValue('cast'); ?>"></label><label>Director<input id="director" type="text" name="director" value="<?php echo $xtreampiSeriesValue('director'); ?>"></label><label>Genres<input id="genre" type="text" name="genre" value="<?php echo $xtreampiSeriesValue('genre'); ?>"></label><label>Release date<input id="release_date" type="text" name="release_date" value="<?php echo $xtreampiSeriesValue('release_date'); ?>"></label><label>Episode runtime<input id="episode_run_time" type="text" name="episode_run_time" value="<?php echo $xtreampiSeriesValue('episode_run_time'); ?>"></label><label>YouTube trailer<input id="youtube_trailer" type="text" name="youtube_trailer" value="<?php echo $xtreampiSeriesValue('youtube_trailer'); ?>"></label><label>Rating<input id="rating" type="text" name="rating" value="<?php echo $xtreampiSeriesValue('rating'); ?>"></label></div></section>
        <div class="sc-form-error" data-sc-serie-error role="alert" hidden></div><div class="sc-form-actions"><button class="sc-button sc-button-primary" type="submit"><?php echo $xtreampiSeriesEditing ? 'Save series' : 'Add series'; ?></button><a class="sc-button sc-button-secondary" href="series">Cancel</a></div>
    </form>
</section>
