<?php

$xtreampiPageScripts = ['assets/xtreampi/server.js'];
$xtreampiServer = is_array($rServerArr ?? null) ? $rServerArr : [];
$xtreampiValue = static fn(string $key, string $default = ''): string => htmlspecialchars((string) ($xtreampiServer[$key] ?? $default), ENT_QUOTES, 'UTF-8');
$xtreampiChecked = static fn(string $key): string => !empty($xtreampiServer[$key]) ? ' checked' : '';
$xtreampiDomains = array_values(array_filter(array_map('trim', explode(',', (string) ($xtreampiServer['domain_name'] ?? '')))));
$xtreampiHttpPorts = array_values(array_filter(array_merge([(string) ($xtreampiServer['http_broadcast_port'] ?? '')], explode(',', (string) ($xtreampiServer['http_ports_add'] ?? ''))), static fn($port) => is_numeric($port) && (int) $port >= 80 && (int) $port <= 65535));
$xtreampiHttpsPorts = array_values(array_filter(array_merge([(string) ($xtreampiServer['https_broadcast_port'] ?? '')], explode(',', (string) ($xtreampiServer['https_ports_add'] ?? ''))), static fn($port) => is_numeric($port) && (int) $port >= 80 && (int) $port <= 65535));
$xtreampiCountries = is_array($rCountries ?? null) ? $rCountries : [];
$xtreampiSelectedCountries = json_decode((string) ($xtreampiServer['geoip_countries'] ?? '[]'), true) ?: [];
$xtreampiInterfaces = array_values(array_unique(array_merge(['auto'], is_array($rInterfaces ?? null) ? $rInterfaces : [])));
$xtreampiGovernors = json_decode((string) ($xtreampiServer['governors'] ?? '[]'), true) ?: [];
$xtreampiCurrentGovernor = json_decode((string) ($xtreampiServer['governor'] ?? '[]'), true);
$xtreampiCurrentGovernor = is_array($xtreampiCurrentGovernor) ? (string) ($xtreampiCurrentGovernor[2] ?? '') : '';
$xtreampiSSLLog = is_array($rSSLLog ?? null) ? $rSSLLog : [];
?>
<section class="sc-server-editor" data-sc-server-editor>
    <div class="sc-page-heading"><div><p class="sc-eyebrow">Infrastructure</p><h1>Edit Server</h1></div><div class="sc-page-actions"><a class="sc-button sc-button-secondary" href="servers"><i class="fe-chevron-left" aria-hidden="true"></i> Back to servers</a></div></div>
    <form class="sc-form" action="post.php?action=server&amp;referer=servers" method="post">
        <input type="hidden" name="edit" value="<?php echo (int) ($xtreampiServer['id'] ?? 0); ?>"><input type="hidden" name="regenerate_ssl" value="0">
        <section class="sc-form-section"><h2>Server details</h2><div class="sc-form-grid">
            <label>Server name<input required name="server_name" value="<?php echo $xtreampiValue('server_name'); ?>"></label><label>Public IP address<input required name="server_ip" inputmode="numeric" value="<?php echo $xtreampiValue('server_ip'); ?>"></label>
            <label>Private IP address<input name="private_ip" inputmode="numeric" value="<?php echo $xtreampiValue('private_ip'); ?>" placeholder="Optional private-network address"></label><label>Maximum clients<input required min="0" type="number" name="total_clients" value="<?php echo $xtreampiValue('total_clients', '0'); ?>"></label>
        </div><div class="sc-package-options sc-line-switches"><label class="sc-selection-card"><input type="checkbox" name="timeshift_only"<?php echo $xtreampiChecked('timeshift_only'); ?>><span><strong>Timeshift only</strong><small>Do not allocate regular client connections.</small></span></label><label class="sc-selection-card"><input type="checkbox" name="enabled"<?php echo !empty($xtreampiServer['is_main']) ? ' checked disabled' : $xtreampiChecked('enabled'); ?>><span><strong>Enabled</strong><small><?php echo !empty($xtreampiServer['is_main']) ? 'The main server is always enabled.' : 'Use this server for streams and client connections.'; ?></small></span></label><?php if (!empty($xtreampiServer['is_main'])): ?><input type="hidden" name="enabled" value="1"><?php endif; ?><label class="sc-selection-card"><input type="checkbox" name="enable_proxy"<?php echo $xtreampiChecked('enable_proxy'); ?>><span><strong>Proxied</strong><small>Route allocated connections through proxies.</small></span></label></div></section>
        <section class="sc-form-section"><h2>Domains and IPs</h2><p class="sc-section-copy">The first entry is used by default; additional entries can be selected randomly for clients.</p><div class="sc-form-grid"><div class="sc-form-span sc-server-tag-editor" data-server-tags data-name="domain_name[]"><label>Domains and IP addresses<input type="text" placeholder="Add a domain or IP, then press Enter" data-server-tag-input></label><div class="sc-token-list" data-server-tag-values><?php foreach ($xtreampiDomains as $xtreampiDomain): ?><span><?php echo htmlspecialchars($xtreampiDomain, ENT_QUOTES, 'UTF-8'); ?><input type="hidden" name="domain_name[]" value="<?php echo htmlspecialchars($xtreampiDomain, ENT_QUOTES, 'UTF-8'); ?>"><button type="button" aria-label="Remove">×</button></span><?php endforeach; ?></div><p data-server-tag-empty<?php echo $xtreampiDomains ? ' hidden' : ''; ?>>No additional domains or IPs.</p></div></div><?php if (empty($xtreampiServer['is_main'])): ?><div class="sc-package-options sc-line-switches"><label class="sc-selection-card"><input type="checkbox" name="random_ip"<?php echo $xtreampiChecked('random_ip'); ?>><span><strong>Serve random domain or IP</strong><small>Choose randomly from the configured entries.</small></span></label></div><?php endif; ?></section>
        <section class="sc-form-section"><h2>Network and delivery</h2><div class="sc-form-grid">
            <div class="sc-server-tag-editor" data-server-tags data-name="http_broadcast_ports[]"><label>HTTP ports<input type="text" inputmode="numeric" placeholder="Add port, then press Enter" data-server-tag-input></label><div class="sc-token-list" data-server-tag-values><?php foreach ($xtreampiHttpPorts as $port): ?><span><?php echo (int) $port; ?><input type="hidden" name="http_broadcast_ports[]" value="<?php echo (int) $port; ?>"><button type="button" aria-label="Remove">×</button></span><?php endforeach; ?></div><p data-server-tag-empty<?php echo $xtreampiHttpPorts ? ' hidden' : ''; ?>>No HTTP ports configured.</p></div>
            <div class="sc-server-tag-editor" data-server-tags data-name="https_broadcast_ports[]"><label>HTTPS ports<input type="text" inputmode="numeric" placeholder="Add port, then press Enter" data-server-tag-input></label><div class="sc-token-list" data-server-tag-values><?php foreach ($xtreampiHttpsPorts as $port): ?><span><?php echo (int) $port; ?><input type="hidden" name="https_broadcast_ports[]" value="<?php echo (int) $port; ?>"><button type="button" aria-label="Remove">×</button></span><?php endforeach; ?></div><p data-server-tag-empty<?php echo $xtreampiHttpsPorts ? ' hidden' : ''; ?>>No HTTPS ports configured.</p></div>
            <label>RTMP port<input type="number" min="1" max="65535" required name="rtmp_port" value="<?php echo $xtreampiValue('rtmp_port', '8880'); ?>"></label><label>Network interface<select name="network_interface"><?php foreach ($xtreampiInterfaces as $interface): ?><option value="<?php echo htmlspecialchars((string) $interface, ENT_QUOTES, 'UTF-8'); ?>"<?php echo (string) ($xtreampiServer['network_interface'] ?? 'auto') === (string) $interface ? ' selected' : ''; ?>><?php echo htmlspecialchars((string) $interface, ENT_QUOTES, 'UTF-8'); ?></option><?php endforeach; ?></select></label>
            <label>Guaranteed network speed (Mbps)<input type="number" min="0" required name="network_guaranteed_speed" value="<?php echo $xtreampiValue('network_guaranteed_speed', '0'); ?>"></label><label>GeoIP priority<select name="geoip_type"><?php foreach (['high_priority' => 'High priority', 'low_priority' => 'Low priority', 'strict' => 'Strict'] as $value => $label): ?><option value="<?php echo $value; ?>"<?php echo ($xtreampiServer['geoip_type'] ?? '') === $value ? ' selected' : ''; ?>><?php echo $label; ?></option><?php endforeach; ?></select></label>
            <label class="sc-form-span">GeoIP countries<select name="geoip_countries[]" multiple size="6"><?php foreach ($xtreampiCountries as $country): ?><option value="<?php echo htmlspecialchars((string) $country['id'], ENT_QUOTES, 'UTF-8'); ?>"<?php echo in_array($country['id'], $xtreampiSelectedCountries) ? ' selected' : ''; ?>><?php echo htmlspecialchars((string) $country['name'], ENT_QUOTES, 'UTF-8'); ?></option><?php endforeach; ?></select></label>
        </div><div class="sc-package-options sc-line-switches"><label class="sc-selection-card"><input type="checkbox" name="disable_ramdisk"<?php echo !empty($rMounted) ? '' : ' checked'; ?>><span><strong>Disable ramdisk</strong><small>Store temporary stream files on disk.</small></span></label><label class="sc-selection-card"><input type="checkbox" name="enable_geoip"<?php echo $xtreampiChecked('enable_geoip'); ?>><span><strong>Enable GeoIP load balancing</strong><small>Use country rules when selecting this server.</small></span></label></div></section>
        <section class="sc-form-section"><h2>Performance</h2><div class="sc-form-grid"><label>PHP services<select name="total_services"><?php foreach (range(1, max(1, (int) ($rServiceMax ?? 4))) as $service): ?><option value="<?php echo $service; ?>"<?php echo (int) ($xtreampiServer['total_services'] ?? 4) === $service ? ' selected' : ''; ?>><?php echo $service; ?></option><?php endforeach; ?></select></label><label>Rate limit per second<input type="number" min="0" required name="limit_requests" value="<?php echo $xtreampiValue('limit_requests', '0'); ?>"></label><label>Rate-limit burst queue<input type="number" min="0" required name="limit_burst" value="<?php echo $xtreampiValue('limit_burst', '0'); ?>"></label><?php if ($xtreampiGovernors): ?><label>CPU governor<select name="governor"><option value="<?php echo htmlspecialchars($xtreampiCurrentGovernor, ENT_QUOTES, 'UTF-8'); ?>"><?php echo htmlspecialchars($xtreampiCurrentGovernor ?: 'Default', ENT_QUOTES, 'UTF-8'); ?></option><?php foreach ($xtreampiGovernors as $governor): if ($governor === $xtreampiCurrentGovernor) continue; ?><option value="<?php echo htmlspecialchars((string) $governor, ENT_QUOTES, 'UTF-8'); ?>"><?php echo htmlspecialchars((string) $governor, ENT_QUOTES, 'UTF-8'); ?></option><?php endforeach; ?></select></label><?php endif; ?><label class="sc-form-span">Custom sysctl.conf<textarea name="sysctl" rows="12"><?php echo $xtreampiValue('sysctl'); ?></textarea></label></div><div class="sc-package-options sc-line-switches"><?php if (!empty($xtreampiServer['is_main'])): ?><label class="sc-selection-card"><input type="checkbox" name="enable_gzip"<?php echo $xtreampiChecked('enable_gzip'); ?>><span><strong>GZIP compression</strong><small>Compress main-server responses.</small></span></label><?php endif; ?></div></section>
        <section class="sc-form-section"><h2>SSL certificate</h2><div class="sc-form-grid"><label>Certificate expiration<input readonly value="<?php echo htmlspecialchars((string) ($rExpiration ?? 'No certificate installed'), ENT_QUOTES, 'UTF-8'); ?>"></label><?php if (!empty($rCertValid)): ?><label>Certificate serial<input readonly value="<?php echo htmlspecialchars((string) ($rCertificate['serial'] ?? ''), ENT_QUOTES, 'UTF-8'); ?>"></label><label class="sc-form-span">Certificate subject<input readonly value="<?php echo htmlspecialchars((string) ($rCertificate['subject'] ?? ''), ENT_QUOTES, 'UTF-8'); ?>"></label><?php endif; ?><?php if (!empty($xtreampiSSLLog['output'])): ?><label class="sc-form-span">Certificate log<textarea readonly rows="7"><?php echo htmlspecialchars(implode("\n", $xtreampiSSLLog['output']), ENT_QUOTES, 'UTF-8'); ?></textarea></label><?php endif; ?></div><div class="sc-package-options sc-line-switches"><label class="sc-selection-card"><input type="checkbox" name="enable_https"<?php echo $xtreampiChecked('enable_https'); ?>><span><strong>Enable HTTPS</strong><small>Allow client connections over TLS.</small></span></label></div><?php if (!empty($xtreampiDomains)): ?><button class="sc-button sc-button-secondary" type="button" data-regenerate-ssl><?php echo !empty($rCertValid) ? 'Force-update SSL' : 'Generate SSL'; ?></button><p class="sc-section-copy">This saves the form and schedules certificate generation for configured domains.</p><?php endif; ?></section>
        <div class="sc-form-error" data-sc-server-error role="alert" hidden></div><div class="sc-form-actions"><button class="sc-button sc-button-primary" type="submit">Save server</button><a class="sc-button sc-button-secondary" href="servers">Cancel</a></div>
    </form>
</section>
