<?php

use XcVm\Core\Auth\Authorization;

$streamcreedPageScripts = ['assets/streamcreed/epg.js'];
$streamcreedEPG = is_array($rEPGArr ?? null) ? $rEPGArr : [];
$streamcreedEditing = !empty($streamcreedEPG['id']);
$streamcreedChannels = json_decode((string) ($streamcreedEPG['data'] ?? '[]'), true) ?: [];
?>
<section class="sc-epg-editor" data-sc-epg-editor><div class="sc-page-heading"><div><p class="sc-eyebrow">Content metadata</p><h1><?php echo $streamcreedEditing ? 'Edit EPG' : 'Add EPG'; ?></h1></div><div class="sc-page-actions"><a class="sc-button sc-button-secondary" href="epgs"><i class="fe-list" aria-hidden="true"></i> Manage EPGs</a></div></div><form class="sc-form" action="post.php?action=epg&amp;referer=epgs" method="post"><?php if ($streamcreedEditing): ?><input type="hidden" name="edit" value="<?php echo (int) $streamcreedEPG['id']; ?>"><?php endif; ?><section class="sc-form-section"><h2>EPG details</h2><div class="sc-form-grid"><label>EPG name<input required name="epg_name" value="<?php echo htmlspecialchars((string) ($streamcreedEPG['epg_name'] ?? ''), ENT_QUOTES, 'UTF-8'); ?>"></label><label class="sc-form-span">Source<input required type="url" name="epg_file" value="<?php echo htmlspecialchars((string) ($streamcreedEPG['epg_file'] ?? ''), ENT_QUOTES, 'UTF-8'); ?>" placeholder="https://example.com/epg.xml.gz"></label><label>Days to keep<input required type="number" min="0" name="days_keep" value="<?php echo htmlspecialchars((string) ($streamcreedEPG['days_keep'] ?? 7), ENT_QUOTES, 'UTF-8'); ?>"></label><label>Minute offset<input required type="number" step="0.5" name="offset" value="<?php echo htmlspecialchars((string) ($streamcreedEPG['offset'] ?? 0), ENT_QUOTES, 'UTF-8'); ?>"></label></div></section><?php if ($streamcreedEditing): ?><section class="sc-form-section"><h2>Channels</h2><div class="sc-data-panel"><div class="sc-table-scroll"><table class="sc-data-table"><thead><tr><th>Key</th><th>Channel name</th><th>Languages</th></tr></thead><tbody><?php foreach ($streamcreedChannels as $key => $channel): ?><tr><td><?php echo htmlspecialchars((string) $key, ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo htmlspecialchars((string) ($channel['display_name'] ?? '—'), ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo htmlspecialchars(implode(', ', (array) ($channel['langs'] ?? [])), ENT_QUOTES, 'UTF-8'); ?></td></tr><?php endforeach; ?><?php if (!$streamcreedChannels): ?><tr><td class="sc-table-state" colspan="3">No channels have been indexed yet.</td></tr><?php endif; ?></tbody></table></div></div></section><?php endif; ?><div class="sc-form-error" data-sc-epg-error hidden></div><div class="sc-form-actions"><button class="sc-button sc-button-primary" type="submit"><?php echo $streamcreedEditing ? 'Save EPG' : 'Add EPG'; ?></button><a class="sc-button sc-button-secondary" href="epgs">Cancel</a></div></form></section>
