<?php

use XcVm\Core\Auth\Authorization;

$streamcreedPageScripts = ['assets/streamcreed/epgs.js'];
$streamcreedCanAdd = Authorization::check('adv', 'add_epg');
$streamcreedCanEdit = Authorization::check('adv', 'epg_edit');
$streamcreedEPGs = is_array($epgs ?? null) ? $epgs : [];
?>
<section class="sc-epgs" data-sc-epgs><div class="sc-page-heading"><div><p class="sc-eyebrow">Content metadata</p><h1>EPG files</h1></div><div class="sc-page-actions"><?php if ($streamcreedCanEdit): ?><button class="sc-button sc-button-secondary" type="button" data-sc-epg-force>Force refresh</button><?php endif; ?><?php if ($streamcreedCanAdd): ?><a class="sc-button sc-button-primary" href="epg"><i class="fe-plus" aria-hidden="true"></i> Add EPG</a><?php endif; ?></div></div><div class="sc-toolbar"><label class="sc-search-field"><i class="fe-search" aria-hidden="true"></i><span class="sc-visually-hidden">Search EPGs</span><input type="search" placeholder="Search EPG name or source" data-sc-epg-search></label></div><div class="sc-data-panel"><div class="sc-table-scroll"><table class="sc-data-table"><thead><tr><th>EPG</th><th>Source</th><th>Days</th><th>Last updated</th><th>Channels</th><th class="sc-col-actions"><span class="sc-visually-hidden">Actions</span></th></tr></thead><tbody data-sc-epg-rows><?php foreach ($streamcreedEPGs as $epg): $id = (int) ($epg['id'] ?? 0); $host = parse_url((string) ($epg['epg_file'] ?? ''), PHP_URL_HOST) ?: 'Local source'; $channels = json_decode((string) ($epg['data'] ?? '[]'), true) ?: []; ?><tr data-sc-epg-row data-search="<?php echo htmlspecialchars(strtolower(($epg['epg_name'] ?? '') . ' ' . ($epg['epg_file'] ?? '')), ENT_QUOTES, 'UTF-8'); ?>"><td><div class="sc-table-identity"><?php if ($streamcreedCanEdit): ?><a href="epg?id=<?php echo $id; ?>"><?php echo htmlspecialchars((string) ($epg['epg_name'] ?? 'Unnamed EPG'), ENT_QUOTES, 'UTF-8'); ?></a><?php else: ?><strong><?php echo htmlspecialchars((string) ($epg['epg_name'] ?? 'Unnamed EPG'), ENT_QUOTES, 'UTF-8'); ?></strong><?php endif; ?><small>#<?php echo $id; ?></small></div></td><td><?php echo htmlspecialchars((string) $host, ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo (int) ($epg['days_keep'] ?? 0); ?></td><td><?php echo !empty($epg['last_updated']) ? date('Y-m-d H:i', (int) $epg['last_updated']) : 'Never'; ?></td><td><?php echo number_format(count($channels)); ?></td><td class="sc-table-actions"><?php if ($streamcreedCanEdit): ?><button class="sc-row-action" type="button" title="Reload EPG" data-sc-epg-action="reload" data-sc-epg-id="<?php echo $id; ?>"><i class="fe-refresh-cw" aria-hidden="true"></i></button><a class="sc-row-action" href="epg?id=<?php echo $id; ?>" title="Edit EPG"><i class="fe-edit-2" aria-hidden="true"></i></a><button class="sc-row-action" type="button" title="Delete EPG" data-sc-epg-action="delete" data-sc-epg-id="<?php echo $id; ?>"><i class="fe-trash-2" aria-hidden="true"></i></button><?php endif; ?></td></tr><?php endforeach; ?><tr data-sc-epg-empty<?php echo $streamcreedEPGs ? ' hidden' : ''; ?>><td class="sc-table-state" colspan="6">No EPG files have been added yet.</td></tr></tbody></table></div></div></section>
