<?php

use XcVm\Core\Auth\Authorization;
use XcVm\Core\Http\RequestManager;
use XcVm\Domain\Server\ServerRepository;

$streamcreedPageScripts = ['assets/streamcreed/episodes.js'];
$streamcreedEpisodeSeries = (int) (RequestManager::getAll()['series'] ?? 0);
$streamcreedCanAddEpisode = Authorization::check('adv', 'add_episode');
$streamcreedCanEditEpisode = Authorization::check('adv', 'edit_episode');
$streamcreedCanConnections = Authorization::check('adv', 'live_connections');
$streamcreedCanPlayEpisode = Authorization::check('adv', 'player');
$streamcreedDefaultEntries = intval($rSettings['default_entries'] ?? 25); if (!in_array($streamcreedDefaultEntries, [10,25,50,100], true)) $streamcreedDefaultEntries = 25;
?>
<section class="sc-episodes" data-sc-episodes data-endpoint="table" data-series="<?php echo $streamcreedEpisodeSeries; ?>" data-can-edit="<?php echo $streamcreedCanEditEpisode ? '1' : '0'; ?>" data-can-connections="<?php echo $streamcreedCanConnections ? '1' : '0'; ?>" data-can-play="<?php echo $streamcreedCanPlayEpisode ? '1' : '0'; ?>" data-show-images="<?php echo !empty($rSettings['show_images']) ? '1' : '0'; ?>">
<div class="sc-page-heading"><div><p class="sc-eyebrow">Series management</p><h1>Episodes</h1></div><div class="sc-page-actions"><a class="sc-button sc-button-secondary" href="series"><i class="fe-chevron-left" aria-hidden="true"></i> Back to series</a><?php if ($streamcreedCanAddEpisode && $streamcreedEpisodeSeries): ?><a class="sc-button sc-button-primary" href="episode?sid=<?php echo $streamcreedEpisodeSeries; ?>"><i class="fe-plus" aria-hidden="true"></i> Add episode</a><?php endif; ?></div></div>
<div class="sc-toolbar"><label class="sc-search-field"><i class="fe-search" aria-hidden="true"></i><span class="sc-visually-hidden">Search episodes</span><input type="search" placeholder="Search episode, series, or source" data-sc-episode-search></label><label class="sc-filter-field"><span>Server</span><select data-sc-episode-server><option value="">All servers</option><option value="-1">No server</option><?php foreach (ServerRepository::getStreamingSimple($rPermissions) as $server): ?><option value="<?php echo (int) $server['id']; ?>"><?php echo htmlspecialchars((string) $server['server_name'], ENT_QUOTES, 'UTF-8'); ?></option><?php endforeach; ?></select></label><label class="sc-filter-field"><span>Status</span><select data-sc-episode-status><option value="">All statuses</option><option value="1">Encoded</option><option value="2">Encoding</option><option value="3">Down</option><option value="4">Ready</option><option value="5">Direct</option></select></label><label class="sc-filter-field"><span>Video</span><select data-sc-episode-video><option value="">Any video</option><option value="-1">No video data</option><?php foreach ($rVideoCodecs as $codec): ?><option value="<?php echo htmlspecialchars((string) $codec, ENT_QUOTES, 'UTF-8'); ?>"><?php echo htmlspecialchars((string) $codec, ENT_QUOTES, 'UTF-8'); ?></option><?php endforeach; ?></select></label><label class="sc-filter-field"><span>Audio</span><select data-sc-episode-audio><option value="">Any audio</option><option value="-1">No audio data</option><?php foreach ($rAudioCodecs as $codec): ?><option value="<?php echo htmlspecialchars((string) $codec, ENT_QUOTES, 'UTF-8'); ?>"><?php echo htmlspecialchars((string) $codec, ENT_QUOTES, 'UTF-8'); ?></option><?php endforeach; ?></select></label><label class="sc-filter-field"><span>Quality</span><select data-sc-episode-resolution><option value="">Any quality</option><?php foreach ([240,360,480,576,720,1080,1440,2160] as $resolution): ?><option value="<?php echo $resolution; ?>"><?php echo $resolution; ?>p</option><?php endforeach; ?></select></label><label class="sc-filter-field sc-entry-field"><span>Per page</span><select data-sc-episode-entries><?php foreach ([10,25,50,100] as $size): ?><option value="<?php echo $size; ?>"<?php echo $size === $streamcreedDefaultEntries ? ' selected' : ''; ?>><?php echo $size; ?></option><?php endforeach; ?></select></label></div>
<div class="sc-data-panel"><div class="sc-table-scroll"><table class="sc-data-table sc-episodes-table"><thead><tr><th>Episode</th><th>Server</th><th>Status</th><th>Clients</th><th>Media info</th><th class="sc-col-actions"><span class="sc-visually-hidden">Actions</span></th></tr></thead><tbody data-sc-episode-rows><tr><td class="sc-table-state" colspan="6">Loading episodes…</td></tr></tbody></table></div><footer class="sc-table-footer"><span data-sc-episode-range>Loading…</span><div class="sc-pagination"><button type="button" data-sc-episode-previous>Previous</button><span data-sc-episode-page>Page 1</span><button type="button" data-sc-episode-next>Next</button></div></footer></div></section>
<dialog class="sc-player-dialog" data-sc-episode-player-dialog aria-label="Episode player"><div class="sc-player-scaler" data-sc-episode-player-scaler><button class="sc-player-close" type="button" data-sc-episode-player-close title="Close (Esc)" aria-label="Close (Esc)">&#215;</button><iframe class="sc-player-frame" data-sc-episode-player-frame allow="autoplay; fullscreen" frameborder="0"></iframe></div></dialog>
