<?php
use XcVm\Domain\Bouquet\BouquetService; use XcVm\Domain\Line\LineRepository; use XcVm\Domain\Server\ServerRepository; use XcVm\Domain\User\UserRepository;
$streamcreedPageScripts=['assets/streamcreed/line_mass.js']; $streamcreedOwners=UserRepository::getRegisteredUsers(); $streamcreedServers=ServerRepository::getAllSimple(); $streamcreedOutputs=LineRepository::getOutputFormats(); $streamcreedBouquets=BouquetService::getAllSimple(); $streamcreedDefaultEntries=intval($rSettings['default_entries']??25); if(!in_array($streamcreedDefaultEntries,[10,25,50,100],true))$streamcreedDefaultEntries=25;
?>
<section class="sc-user-mass" data-sc-line-mass><div class="sc-page-heading"><div><p class="sc-eyebrow">Subscriber Access</p><h1>Mass Edit Subscriptions <small data-sc-selected-count></small></h1></div><div class="sc-page-actions"><a class="sc-button sc-button-secondary" href="lines"><i class="fe-chevron-left"></i> Back to subscriptions</a></div></div>
<form class="sc-form sc-mass-form" action="post.php?action=line_mass" method="post" enctype="multipart/form-data"><input type="hidden" name="users_selected" value="[]"><input type="hidden" name="bouquets_selected" value="[]">
<section class="sc-form-section"><h2>Select Subscriptions</h2><div class="sc-selection-summary" data-sc-selection-summary hidden><span><strong data-sc-selection-total>0</strong> subscriptions selected across all pages</span><button type="button" data-sc-clear-selection>Clear selection</button></div><div class="sc-toolbar"><label class="sc-search-field"><i class="fe-search"></i><span class="sc-visually-hidden">Search subscriptions</span><input type="search" placeholder="Search subscriptions" data-sc-mass-search></label><label class="sc-filter-field"><span>Status</span><select data-sc-mass-filter><option value="">All statuses</option><option value="1">Active</option><option value="2">Disabled</option><option value="3">Banned</option><option value="4">Expired</option><option value="5">Trial</option><option value="6">Restreamer</option><option value="7">Ministra</option></select></label><label class="sc-filter-field"><span>Per page</span><select data-sc-mass-entries><?php foreach([10,25,50,100] as $size):?><option<?php echo $size===$streamcreedDefaultEntries?' selected':'';?>><?php echo $size;?></option><?php endforeach;?></select></label></div><div class="sc-data-panel"><div class="sc-table-scroll"><table class="sc-data-table"><thead><tr><th class="sc-select-column"><input type="checkbox" data-sc-select-page></th><th>Subscription</th><th>Owner</th><th>Status</th><th>Connections</th><th>Expiration</th></tr></thead><tbody data-sc-mass-rows><tr><td colspan="6" class="sc-table-state">Loading subscriptions…</td></tr></tbody></table></div><footer class="sc-table-footer"><span data-sc-mass-range></span><div class="sc-pagination"><button type="button" data-sc-previous>Previous</button><span data-sc-page>Page 1</span><button type="button" data-sc-next>Next</button></div></footer></div></section>
<section class="sc-form-section"><h2>Choose Changes</h2><p class="sc-section-copy">Enable only the values you want to update. Everything else remains unchanged.</p><div class="sc-mass-change-grid">
<?php $owners=''; foreach($streamcreedOwners as $owner)$owners.='<option value="'.intval($owner['id']).'">'.htmlspecialchars((string)$owner['username'],ENT_QUOTES,'UTF-8').'</option>'; $servers='<option value="0">Disabled</option>'; foreach($streamcreedServers as $server)$servers.='<option value="'.intval($server['id']).'">'.htmlspecialchars((string)$server['server_name'],ENT_QUOTES,'UTF-8').'</option>'; ?>
<div class="sc-mass-change"><label class="sc-check"><input type="checkbox" name="c_member_id" data-sc-activate="member_id"><span>Change owner</span></label><label>Owner<select name="member_id" disabled><?php echo $owners;?></select></label></div>
<div class="sc-mass-change"><label class="sc-check"><input type="checkbox" name="c_max_connections" data-sc-activate="max_connections"><span>Change connection limit</span></label><label>Maximum Connections<input type="number" min="0" name="max_connections" value="1" disabled></label></div>
<div class="sc-mass-change"><label class="sc-check"><input type="checkbox" name="c_exp_date" data-sc-activate-group="expiration"><span>Change expiration</span></label><label>Expiration<input type="datetime-local" name="exp_date" disabled></label><label class="sc-check"><input type="checkbox" name="no_expire" disabled data-sc-expire-never><span>Never expires</span></label></div>
<div class="sc-mass-change"><label class="sc-check"><input type="checkbox" name="c_force_server_id" data-sc-activate="force_server_id"><span>Change forced connection</span></label><label>Server<select name="force_server_id" disabled><?php echo $servers;?></select></label></div>
<div class="sc-mass-change"><label class="sc-check"><input type="checkbox" name="c_admin_notes" data-sc-activate="admin_notes"><span>Change admin notes</span></label><label>Admin Notes<textarea name="admin_notes" disabled></textarea></label></div>
<div class="sc-mass-change"><label class="sc-check"><input type="checkbox" name="c_reseller_notes" data-sc-activate="reseller_notes"><span>Change reseller notes</span></label><label>Reseller Notes<textarea name="reseller_notes" disabled></textarea></label></div>
<?php foreach([['is_stalker','Ministra portal'],['is_restreamer','Restreamer'],['is_isplock','ISP lock'],['is_trial','Trial account']] as [$key,$label]):?><div class="sc-mass-change"><label class="sc-check"><input type="checkbox" name="c_<?php echo $key;?>" data-sc-activate="<?php echo $key;?>"><span>Change <?php echo strtolower($label);?></span></label><label class="sc-check sc-mass-value"><input type="checkbox" name="<?php echo $key;?>" disabled><span><?php echo $label;?> enabled</span></label></div><?php endforeach;?>
<div class="sc-mass-change"><label class="sc-check"><input type="checkbox" name="c_forced_country" data-sc-activate="forced_country"><span>Change forced country</span></label><label>Country<select name="forced_country" disabled><?php foreach(($rCountries??[]) as $country):?><option value="<?php echo htmlspecialchars((string)$country['id'],ENT_QUOTES,'UTF-8');?>"><?php echo htmlspecialchars((string)$country['name'],ENT_QUOTES,'UTF-8');?></option><?php endforeach;?></select></label></div>
<div class="sc-mass-change"><label class="sc-check"><input type="checkbox" name="c_access_output" data-sc-activate-group="outputs"><span>Change output formats</span></label><div data-sc-output-fields><?php foreach($streamcreedOutputs as $output):?><label class="sc-check"><input type="checkbox" name="access_output[]" value="<?php echo intval($output['access_output_id']);?>" checked disabled><span><?php echo htmlspecialchars((string)$output['output_name'],ENT_QUOTES,'UTF-8');?></span></label><?php endforeach;?></div></div>
<div class="sc-mass-change"><label class="sc-check"><input type="checkbox" name="reset_isp_lock"><span>Reset current ISP lock</span></label></div>
</div></section>
<section class="sc-form-section"><div class="sc-section-heading"><h2>Bouquets</h2><label class="sc-check"><input type="checkbox" name="c_bouquets"><span>Apply bouquet selection</span></label></div><div class="sc-selection-grid" data-sc-bouquets><?php foreach($streamcreedBouquets as $bouquet):?><label class="sc-selection-card"><input type="checkbox" value="<?php echo intval($bouquet['id']);?>"><span><strong><?php echo htmlspecialchars((string)$bouquet['bouquet_name'],ENT_QUOTES,'UTF-8');?></strong></span></label><?php endforeach;?></div></section>
<div class="sc-form-error" data-sc-mass-error hidden></div><div class="sc-mass-actions"><p data-sc-action-summary>Select subscriptions and choose at least one change.</p><div class="sc-form-actions"><button class="sc-button sc-button-primary" type="submit" name="submit_line" value="Mass Edit" data-sc-submit disabled>Apply Changes</button><a class="sc-button sc-button-secondary" href="lines">Cancel</a></div></div></form></section>
