<?php
use XcVm\Core\Auth\Authorization;
$streamcreedPageScripts=['assets/streamcreed/mags.js'];$streamcreedCanAdd=Authorization::check('adv','add_mag');$streamcreedCanEdit=Authorization::check('adv','edit_mag');$streamcreedDefaultEntries=intval($rSettings['default_entries']??25);if(!in_array($streamcreedDefaultEntries,[10,25,50,100],true))$streamcreedDefaultEntries=25;
?>
<section data-sc-mags data-endpoint="table" data-default-entries="<?php echo $streamcreedDefaultEntries;?>" data-can-edit="<?php echo $streamcreedCanEdit?'1':'0';?>">
 <div class="sc-page-heading"><div><p class="sc-eyebrow">Devices</p><h1>MAG Devices</h1></div><div class="sc-page-actions"><?php if($streamcreedCanAdd):?><a class="sc-button sc-button-primary" href="mag"><i class="fe-plus"></i> Add device</a><?php endif;?></div></div>
 <div class="sc-toolbar"><label class="sc-search-field"><i class="fe-search"></i><input type="search" placeholder="Search user, MAC, device, or expiration" data-search></label><label class="sc-filter-field"><span>Status</span><select data-filter><option value="">All devices</option><option value="1">Active</option><option value="2">Disabled</option><option value="3">Banned</option><option value="4">Expired</option><option value="5">Trial</option></select></label><label class="sc-filter-field sc-entry-field"><span>Per page</span><select data-entries><?php foreach([10,25,50,100] as $size):?><option value="<?php echo $size;?>"<?php echo $size===$streamcreedDefaultEntries?' selected':'';?>><?php echo $size;?></option><?php endforeach;?></select></label></div>
 <div class="sc-data-panel"><div class="sc-table-scroll"><table class="sc-data-table"><thead><tr><th>MAC address</th><th>Device</th><th>Owner</th><th>Status</th><th>Online</th><th>Trial</th><th>Expiration</th><th>Last connection</th><th></th></tr></thead><tbody data-rows><tr><td class="sc-table-state" colspan="9">Loading devices…</td></tr></tbody></table></div><footer class="sc-table-footer"><span data-range>Loading…</span><div class="sc-pagination"><button data-prev>Previous</button><span data-page>Page 1</span><button data-next>Next</button></div></footer></div>
</section>
