<?php
$streamcreedPageScripts = ['assets/streamcreed/process_monitor.js'];
$streamcreedServerId = intval($_GET['server'] ?? (defined('SERVER_ID') ? SERVER_ID : 1));
$streamcreedServers = is_array($rServers ?? null) ? $rServers : [];
$streamcreedFilesystem = is_array($rFS ?? null) ? $rFS : [];
$streamcreedProcesses = is_array($rProcesses ?? null) ? $rProcesses : [];
?>
<section class="sc-process-monitor" data-sc-process-monitor>
<div class="sc-page-heading"><div><p class="sc-eyebrow">System</p><h1>Process Monitor</h1></div><div class="sc-page-actions"><a class="sc-button sc-button-secondary" href="process_monitor?server=<?php echo $streamcreedServerId; ?>"><i class="fe-refresh-cw" aria-hidden="true"></i> Refresh</a></div></div>
<?php if ($streamcreedFilesystem): ?><div class="sc-data-panel sc-process-filesystem"><div class="sc-table-scroll"><table class="sc-data-table"><thead><tr><th>Mount point</th><th>Size</th><th>Used</th><th>Available</th><th>Used %</th><th>Actions</th></tr></thead><tbody><?php foreach ($streamcreedFilesystem as $streamcreedFs): ?><tr><td><?php echo htmlspecialchars((string) ($streamcreedFs['mount'] ?? '—'), ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo htmlspecialchars((string) ($streamcreedFs['size'] ?? '—'), ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo htmlspecialchars((string) ($streamcreedFs['used'] ?? '—'), ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo htmlspecialchars((string) ($streamcreedFs['avail'] ?? '—'), ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo htmlspecialchars((string) ($streamcreedFs['percentage'] ?? '0%'), ENT_QUOTES, 'UTF-8'); ?></td><td class="sc-table-actions">—</td></tr><?php endforeach; ?></tbody></table></div></div><?php endif; ?>
<div class="sc-data-panel"><div class="sc-process-toolbar"><label class="sc-search-field"><i class="fe-search" aria-hidden="true"></i><span class="sc-visually-hidden">Search processes</span><input type="search" placeholder="Search processes…" data-sc-process-search></label><label class="sc-filter-field"><span>Server</span><select onchange="location.href='process_monitor?server='+encodeURIComponent(this.value)"><?php foreach ($streamcreedServers as $streamcreedServer): ?><option value="<?php echo intval($streamcreedServer['id']); ?>"<?php echo intval($streamcreedServer['id']) === $streamcreedServerId ? ' selected' : ''; ?>><?php echo htmlspecialchars((string) ($streamcreedServer['server_name'] ?? 'Server'), ENT_QUOTES, 'UTF-8'); ?></option><?php endforeach; ?></select></label></div><div class="sc-table-scroll"><table class="sc-data-table"><thead><tr><th>PID</th><th>Type</th><th>Process</th><th>CPU (%)</th><th>MEM (MB)</th><th>Runtime</th><th>CPU time</th><th>Actions</th></tr></thead><tbody data-sc-process-rows><?php foreach ($streamcreedProcesses as $streamcreedProcess): ?><tr data-sc-process-row data-search="<?php echo htmlspecialchars(strtolower((string) ($streamcreedProcess['pid'] ?? '') . ' ' . (string) ($streamcreedProcess['command'] ?? '')), ENT_QUOTES, 'UTF-8'); ?>"><td><?php echo intval($streamcreedProcess['pid'] ?? 0); ?></td><td>System</td><td><?php echo htmlspecialchars((string) ($streamcreedProcess['command'] ?? '—'), ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo number_format((float) ($streamcreedProcess['cpu'] ?? 0), 2); ?>%</td><td><?php echo number_format((float) ($streamcreedProcess['rss'] ?? 0) / 1024, 0); ?></td><td>—</td><td>—</td><td class="sc-table-actions">—</td></tr><?php endforeach; ?><?php if (!$streamcreedProcesses): ?><tr><td class="sc-table-state" colspan="8">Unable to retrieve process list. Try refreshing the monitor.</td></tr><?php endif; ?></tbody></table></div></div>
</section>
