<?php

use XcVm\Core\Http\RequestManager;

$streamcreedPageScripts = ['assets/streamcreed/server-install.js'];
$streamcreedType = (int) ($rType ?? 2);
$streamcreedProxy = $streamcreedType === 1;
$streamcreedExisting = is_array($rServerArr ?? null) ? $rServerArr : null;
$streamcreedUpdating = isset(RequestManager::getAll()['update']);
$streamcreedParents = $streamcreedExisting ? ($streamcreedExisting['parent_id'] ?? []) : [];
if (is_string($streamcreedParents)) $streamcreedParents = json_decode($streamcreedParents, true) ?: [];
?>
<section class="sc-server-install" data-sc-server-install data-proxy="<?php echo $streamcreedProxy ? '1' : '0'; ?>">
    <div class="sc-page-heading"><div><p class="sc-eyebrow">Infrastructure</p><h1><?php echo $streamcreedExisting ? ($streamcreedUpdating ? 'Update' : 'Reinstall') : 'Install'; ?> <?php echo $streamcreedProxy ? 'Proxy' : 'Server'; ?></h1></div><div class="sc-page-actions"><a class="sc-button sc-button-secondary" href="servers"><i class="fe-chevron-left" aria-hidden="true"></i> Back to servers</a></div></div>
    <?php if ($streamcreedExisting && !empty($streamcreedExisting['is_main'])): ?><div class="sc-form-error">The main server cannot be reinstalled from the admin panel.</div><?php else: ?><form class="sc-form" action="post.php?action=server_install&amp;referer=servers" method="post"><input type="hidden" name="type" value="<?php echo $streamcreedType; ?>"><input type="hidden" name="parent_id" value="[]"><?php if ($streamcreedExisting): ?><input type="hidden" name="edit" value="<?php echo (int) $streamcreedExisting['id']; ?>"><?php endif; ?>
        <section class="sc-form-section"><h2>Connection details</h2><div class="sc-form-grid"><label>Server name<input required name="server_name"<?php echo $streamcreedExisting ? ' readonly' : ''; ?> value="<?php echo htmlspecialchars((string) ($streamcreedExisting['server_name'] ?? ''), ENT_QUOTES, 'UTF-8'); ?>"></label><label>Server IP address<input required name="server_ip" inputmode="numeric"<?php echo $streamcreedExisting ? ' readonly' : ''; ?> value="<?php echo htmlspecialchars((string) ($streamcreedExisting['server_ip'] ?? ''), ENT_QUOTES, 'UTF-8'); ?>"></label><label>SSH port<input required type="number" min="1" max="65535" name="ssh_port" value="22"></label><label>SSH username<input required name="root_username" value="root"></label><label class="sc-form-span">SSH password<input required type="password" name="root_password" autocomplete="new-password"></label><?php if ($streamcreedProxy): ?><label>HTTP port<input required type="number" min="1" max="65535" name="http_broadcast_port" value="80"></label><label>HTTPS port<input required type="number" min="1" max="65535" name="https_broadcast_port" value="443"></label><?php endif; ?></div><div class="sc-package-options sc-line-switches"><label class="sc-selection-card"><input type="checkbox" name="update_sysctl" checked><span><strong>Update sysctl.conf</strong><small>Apply XC_VM’s network and file-limit defaults.</small></span></label><?php if ($streamcreedProxy): ?><label class="sc-selection-card"><input type="checkbox" name="use_private_ip"><span><strong>Use private IP</strong><small>Route proxy traffic internally to its load balancers.</small></span></label><?php endif; ?></div></section>
        <?php if ($streamcreedProxy): ?><section class="sc-form-section"><h2>Server coverage</h2><p class="sc-section-copy">Select at least one streaming server that this proxy should serve.</p><div class="sc-server-placement" data-sc-proxy-parents><?php foreach ($rServers as $streamcreedServer): if ((int) ($streamcreedServer['server_type'] ?? 0) !== 0) continue; ?><label class="sc-selection-card"><input type="checkbox" value="<?php echo (int) $streamcreedServer['id']; ?>"<?php echo in_array((int) $streamcreedServer['id'], array_map('intval', $streamcreedParents), true) ? ' checked' : ''; ?>><span><strong><?php echo htmlspecialchars((string) $streamcreedServer['server_name'], ENT_QUOTES, 'UTF-8'); ?></strong><small><?php echo htmlspecialchars((string) $streamcreedServer['server_ip'], ENT_QUOTES, 'UTF-8'); ?></small></span></label><?php endforeach; ?></div></section><?php endif; ?>
        <section class="sc-form-section"><h2>Provisioning notice</h2><p class="sc-section-copy"><?php echo $streamcreedUpdating ? 'Updating will reinstall the server with the current XC_VM software. The server will be unavailable during the process.' : ($streamcreedExisting ? 'Reinstalling takes the server offline until provisioning completes.' : 'Provisioning begins immediately after you submit. Progress is available from Server Monitor.'); ?></p></section>
        <div class="sc-form-error" data-sc-server-install-error hidden></div><div class="sc-form-actions"><button class="sc-button sc-button-primary" type="submit"><?php echo $streamcreedExisting ? ($streamcreedUpdating ? 'Update' : 'Reinstall') : 'Install'; ?> <?php echo $streamcreedProxy ? 'proxy' : 'server'; ?></button><a class="sc-button sc-button-secondary" href="servers">Cancel</a></div>
    </form><?php endif; ?>
</section>
